#--------Multiple Linear Regression-----------

    An extension of simple linear regression. In simple linear regression
    there is a one-to-one relationship between the input variable and the
    output variable. But in multiple linear regression, as the name implies
    there is a many-to-one relationship, instead of just using one input variable.
    
    The model for multiple linear regression is as you would expect,
    very similar to the one for simple linear regression. It goes as follows:
    
    f(X) = a + (B1 * X1) + (B2 * X2) … + (Bp * Xp).
    
    Where X is the input variables and Xp is a specific input variable,
    Bp is the coefficient (slope) of the input variable Xp and a is the
    intercept. Let’s test this out with an example!

Note :- In this example we have used linear regresion model on this
        but we did'nt get that much accuracy so we can also use alternatives
        that is Ridge and Lasso models they will give better accuracy than Linear 
        Regression on this dataset.

In [1]:
#Importing our libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Getting our data and cleaning data

dataset = pd.read_csv('Downloads/housingdata.csv')
dataset = dataset.dropna()
dataset.head()

0.00632   18  2.31  0  0.538  6.575  65.2    4.09  1  296  15.3   396.9  \
0  0.02731  0.0  7.07  0  0.469  6.421  78.9  4.9671  2  242  17.8  396.90   
1  0.02729  0.0  7.07  0  0.469  7.185  61.1  4.9671  2  242  17.8  392.83   
2  0.03237  0.0  2.18  0  0.458  6.998  45.8  6.0622  3  222  18.7  394.63   
3  0.06905  0.0  2.18  0  0.458  7.147  54.2  6.0622  3  222  18.7  396.90   
4  0.02985  0.0  2.18  0  0.458  6.430  58.7  6.0622  3  222  18.7  394.12   

   4.98    24  
0  9.14  21.6  
1  4.03  34.7  
2  2.94  33.4  
3  5.33  36.2  
4  5.21  28.7

In [3]:
#Getting X_data

X_data = dataset.iloc[:,0:-1].values
X_data[0:5]

array([[2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9463e+02, 2.9400e+00],
       [6.9050e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        7.1470e+00, 5.4200e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9690e+02, 5.3300e+00],
       [2.9850e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.4300e+00, 5.8700e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9412e+02, 5.2100e+00]])

In [4]:
#Getting Y_data

Y_data = dataset.iloc[:,-1].values
Y_data[0:5]

array([21.6, 34.7, 33.4, 36.2, 28.7])

In [5]:
#Splitting data into training testing

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X_data,Y_data,test_size=0.3)

In [6]:
#Scaling the data

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_data = scaler.fit_transform(X_data)

In [7]:
# Importing our classifier

from sklearn.linear_model import LinearRegression
classifier = LinearRegression()
classifier.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
#Checking accuracy on training data to see if our model is overfitting
#or not

classifier.score(x_train,y_train)

0.7464287251743658

In [9]:
#Testing classifier on testing data

from sklearn.model_selection import cross_val_score
results = cross_val_score(classifier,x_test,y_test,cv=5)
print(results)

[0.55402954 0.78102248 0.65011931 0.54583417 0.52691887]


In [ ]:
#In best case scenario we got accuracy score of 78%